Added symbols icon and fraction key to second page
simpleclub/math_keyboard pull request #26
Opened 2022-01-04 09:34 UTC by tomkuschka

## Description

This PR adds a new icon for the symbols page and a fraction button to the second page of the keyboard

| New icon for symbols | Fraction button |
|---|---|
|![image](https://user-images.githubusercontent.com/35028202/148037947-26e88c58-294f-4035-94a9-99debd7b1d34.png)|![image](https://user-images.githubusercontent.com/35028202/148037958-a8ecd772-6f1a-44bf-9748-0389756c0d6e.png)|

## Checklist

*Remove `If [...]` items that do not apply to your PR.*

- [x] I have made myself familiar with the CaTeX
      [contributing guide](https://github.com/simpleclub/math_keyboard/blob/master/CONTRIBUTING.md).
- [x] I added a PR description.
- [x] If this PR changes anything about the main `math_keyboard` or `example` package
      (also README etc.), I created an entry in `CHANGELOG.md` (`## UPCOMING RELEASE` if the change
      on its own is not worth an update).
- [x] If this PR includes a notable change in the `math_keyboard` package, I updated the version
        according to [Dart's semantic versioning](https://stackoverflow.com/questions/66201337/how-do-dart-package-versions-work-how-should-i-version-my-flutter-plugins/66201338#66201338).
- [ ] All required checks pass.

2022-01-04 10:00 UTC, edhom commented on math_keyboard/lib/src/widgets/math_keyboard.dart
> +                            // label: controller.secondPage ? '123' : 'f(x)',
```suggestion
```

2022-01-04 10:00 UTC, edhom approved these changes
lgtm

2022-01-04 14:41 UTC, edhom submitted a review, later dismissed

2022-01-04 15:58 UTC, ukasz123 submitted a review, later dismissed

2022-01-04 23:36 UTC, creativecreatorormaybenot requested changes
Otherwise, LGTM 🔥🔥

2022-01-05 00:00 UTC, creativecreatorormaybenot submitted a review, later dismissed
Do not want to delay you :P

Feel free to adjust :)

2022-01-05 00:01 UTC, creativecreatorormaybenot commented
(but would be cool if you replace the accent color usage by color scheme secondary :D)

2022-01-05 09:23 UTC, edhom approved these changes

2022-01-05 17:33 UTC, creativecreatorormaybenot approved these changes

2022-01-05 17:34 UTC, merged